drupaldb:
  image: mariadb
  restart: always
  environment:
  - MYSQL_ROOT_PASSWORD=Passw0rd
  - MYSQL_USER=drupaladmin
  - MYSQL_PASSWORD=Passw0rd
  - MYSQL_DATABASE=drupaldb
  # host volume
  volumes:
    - ./data/var/lib/mysql:/var/lib/mysql

drupalweb:
  image: drupal
  restart: always
  ports:
  - "2080:80"
  - "2443:443"
  links:
  - drupaldb
